swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: My League
  
produces:
  - application/json

paths:
  /leagues:
    # This is a HTTP operation
    get:
      summary: Leagues
      description: |
        The leagues endpoint returns information about
        the leagues registered in the system
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
        - name: type
          in: query
          description: Type of the league.
          required: false
          type: string
        - name: name
          in: query
          description: Name of the league.
          required: false
          type: string          
      tags:
        - Leagues
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response. An array of leagues.
          schema:
            title: league
            type: array
            items:
              $ref: '#/definitions/League'
        # Response code
        400:
          description: Failure response. Bad request.        
        404:
          description: Failure response. Leagues not found.
    post:
      summary: Create new league
      description: |
        The leagues endpoint creates new legue in the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: new league properties.
          required: true
          schema:
            title: league
            type: object
            items:
              $ref: '#/definitions/League'
      responses:
        # Response code
        201:
          description: Created
        500:
          description: Internal Server Error
        400:
          description: Bad Request
        409:
          description: Conflict          
definitions:
  League:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a league.
      type:
        type: string
        description: The type of league.
      name:
        type: string
        description: Display name of league.
      teams:
        type: array
        description: collection of team IDs
        items:
          type: string
      seasons:
        type: array
        items:
          $ref: '#/definitions/Season'
      association:
        type: string
        description: The association to which the league belong.
      address:
        $ref: '#/definitions/Address'
      image:
        type: string
        description: Image URL representing the league.
      last_updated:
        type: string
        description: The date of last update.
  Team:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a team.
      name:
        type: string
        description: Display name of team.
      coach:
        type: string
        description: The id of coach.
      captain:
        type: string
        description: The id of captain.
      players:
        type: array
        items:
          $ref: '#/definitions/Player'
      colors:
        type: array
        items:
          $ref: '#/definitions/Color'
      status:
        type: string
        description: The status of the team.
      image:
        type: string
        description: Image URL representing the league.
  Season:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a season.
  Color:
    type: object
    properties:
      home:
        type: string
        description: The home team color.
      away:
        type: string
        description: The away team color.
  Contact:
    type: object
    properties:
      phone:
        type: string
        description: The phone number.
      email:
        type: string
        description: The email address.
  Document:
    type: object
    properties:
      season:
        type: string
        description: The season id.
      document:
        type: string
        description: The link to a document.
  Access:
    type: object
    properties:
      level:
        type: string
        description: The access level.
      group:
        type: string
        description: The access group.
  Payment:
    type: object
    properties:
      season:
        type: string
        description: The season id.
      method:
        type: string
        description: The payment method.
        enum:
         - check
         - cash
         - direct deposit
  Notification:
    type: object
    properties:
      id:
        type: string
        description: The id of notification.
      person_id:
        type: string
        description: The person id.
      category:
        type: string
        description: The category of notification.
        enum:
         - action
         - info
      priority:
        type: string
        description: The priority of notification.
      type:
        type: string
        description: The type of notification.
        enum:
         - join team
         - leave team
      parameters:
        type: array
        description: The additional parameters of notification.
        items:
            type: object
            properties:
              name:
                type: string
                description: The name of the parameter.
              value:
                type: string
                description: The value of the parameter.         
  Address:
    type: object
    properties:
      street:
        type: string
        description: The street.
      city:
        type: string
        description: The city.
      city:
        type: string
        description: The city.
      state:
        type: string
        description: The state.
      zip:
        type: string
        description: The zip code.
  Player:
    type: object
    properties:
      id:
        type: string
        description: The id of the player.
      person_id:
        type: string
        description: The id of the person.
      shirtnumber:
        type: string
        description: The number of shirt.
      position:
        type: string
        description: The position of the player.
  Person:
    type: object
    properties:
     id:
      type: string
      description: The ID of the person
     login:
      type: string
      description: The login of the person
     password:
      type: string
      description: The password of the person
     first_name:
      type: string
      description: First name
     last_name:
      type: string
      description: Last name      
     gender:
      type: string
      description: The gender of the person
     address:
      $ref: '#/definitions/Address'
     birth:
      type: string
      description: The birth date of the person
     photo:
      type: string
      description: The photo of the person
     contact:
      $ref: '#/definitions/Contact'
     documents:
      type: array
      items:
       $ref: '#/definitions/Document'
     payments:
      type: array
      items:
       $ref: '#/definitions/Payment'
     role:
      type: string
      description: The natural position of the person
     access_level:
      $ref: '#/definitions/Access'
     status:
      type: string
      description: Last name
      enum:
       - active
       - injured
       - inactive
     notifications:
      type: array
      items:
       $ref: '#/definitions/Notification'
     
